services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: materialize-nextjs-admin
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - pnpm-store:/root/.pnpm-store
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  pnpm-store:
    # Persistent volume for pnpm store to speed up subsequent builds
