export const campaignStatusType = [
  { name: 'One Time', value: 'one_time' },
  { name: 'Recurring', value: 'recurring' },
  { name: 'In Progress', value: 'in_progress' }
]
export const publishingModeType = [
  { name: 'Recurring', value: 'recurring' },
  { name: 'One Time', value: 'one_time' }
]
export const scheduleTypeDropDown = [
  { name: 'Now', value: 'now' },
  { name: 'Schedule', value: 'schedule' }
]
export const frequencyTypeDropDown = [
  { name: 'Day', value: 'day' },
  { name: 'Week', value: 'week' },
  { name: 'Month', value: 'month' },
  { name: 'Year', value: 'year' }
]

export const statusTypeDropDown = [
  { id: '1', name: 'Draft' },
  { id: '2', name: 'Ready to Publish' },
  { id: '3', name: 'Published' }
]
export const salutationtitleDropDown = [
  {  name: 'Dr', value: 'Dr' },
  {  name: 'Miss', value: 'Miss' },
  {  name: 'Mr', value: 'Mr' },
  {  name: 'Mrs', value: 'Mrs' },
  {  name: 'Ms', value: 'Ms' }
]
export const genderDropDown = [
  { name: 'Male', value: 'male' },
  { name: 'Female', value: 'female' },
  { name: 'Other', value: 'other' }
]

export const contactTypeDropDown = [
  { name: '1', value: 1 },
  { name: '2', value: 2 },
  { name: '3', value: 3 },
  { name: '4', value: 4 },
  { name: '5', value: 5 },
  { name: '6', value: 6 },
  { name: '7', value: 7 },
  { name: '8', value: 8 },
]

export const employeeStatusDropDown = [
  { name: 'Casual', value: 'Casual' },
  { name: 'Full Time', value: 'Full Time' },
  { name: 'Part Time', value: 'Part Time' }
]


export const awardCodeDropDown = [
  { name: 'CO', value: 'CO' },
  { name: 'EC', value: 'EC' },
  { name: 'NU', value: 'NU' },
  { name: 'SO', value: 'SO' },
  { name: 'TE', value: 'TE' },
  { name: 'YC', value: 'YC' }
]

export const awardDescriptionDropDown = [
  { name: 'Early Childhood Education Work', value: 'EC' },
  { name: 'EBA - Nurse', value: 'NU' },
  { name: 'EBA - School Officers', value: 'SO' },
  { name: 'EBA - Teachers', value: 'TE' },
  { name: 'MA000076 Children Young Worker', value: 'YC' },
  { name: 'Other Officer', value: 'CO' }
]


export const roleCodeDropDown = [
  { name: 'CGL1', value: 'CGL1' },
  { name: 'CGL2', value: 'CGL2' },
  { name: 'CGL5', value: 'CGL5' },
  { name: 'CSEL1P1', value: 'CSEL1P1' },
  { name: 'CSEL2P1', value: 'CSEL2P1' },
  { name: 'CSEL2P2', value: 'CSEL2P2' },
  { name: 'CSEL3P4', value: 'CSEL3P4' },
  { name: 'CSEL4AP1', value: 'CSEL4AP1' },
  { name: 'CSEL4P3M', value: 'CSEL4P3M' },
  { name: 'CSEL6P4', value: 'CSEL6P4' },
  { name: 'CSELSBT', value: 'CSELSBT' },
  { name: 'DOSS', value: 'DOSS' },
  { name: 'DSL1PP23', value: 'DSL1PP23' },
  { name: 'DSL2PP33', value: 'DSL2PP33' },
  { name: 'DSL3PP33', value: 'DSL3PP33' },
  { name: 'DSL3PP34', value: 'DSL3PP34' },
  { name: 'DSL3PP35', value: 'DSL3PP35' },
  { name: 'EXEP', value: 'EXEP' },
  { name: 'JUNIOR11', value: 'JUNIOR11' },
  { name: 'JUNIOR5', value: 'JUNIOR5' },
  { name: 'JUNIOR7', value: 'JUNIOR7' },
  { name: 'JUNIOR9', value: 'JUNIOR9' },
  { name: 'L1S119', value: 'L1S119' },
  { name: 'L2S119', value: 'L2S119' },
  { name: 'NSG1', value: 'NSG1' },
  { name: 'NSG2S2', value: 'NSG2S2' },
  { name: 'OEBA1', value: 'OEBA1' },
  { name: 'OEBA4', value: 'OEBA4' },
  { name: 'OEBA5', value: 'OEBA5' },
  { name: 'OEBA5B', value: 'OEBA5B' },
  { name: 'OEBA6', value: 'OEBA6' },
  { name: 'OEBA7A', value: 'OEBA7A' },
  { name: 'OEBA7B', value: 'OEBA7B' },
  { name: 'OEBA8', value: 'OEBA8' },
  { name: 'OEBA8A', value: 'OEBA8A' },
  { name: 'OEBA9', value: 'OEBA9' },
  { name: 'OEBAM', value: 'OEBAM' },
  { name: 'S2L1PP02', value: 'S2L1PP02' },
  { name: 'SL1PP13', value: 'SL1PP13' },
  { name: 'SSL1S1', value: 'SSL1S1' },
  { name: 'SSL2S1', value: 'SSL2S1' },
  { name: 'SSL2S2', value: 'SSL2S2' },
  { name: 'SSL2S3', value: 'SSL2S3' },
  { name: 'SSL3S1', value: 'SSL3S1' },
  { name: 'SSL3S2', value: 'SSL3S2' },
  { name: 'SSL3S3', value: 'SSL3S3' },
  { name: 'SSL3S4', value: 'SSL3S4' },
  { name: 'SSL4S1', value: 'SSL4S1' },
  { name: 'SSL4S2', value: 'SSL4S2' },
  { name: 'SSL4S3', value: 'SSL4S3' },
  { name: 'SSL5S1', value: 'SSL5S1' },
  { name: 'SSL5S2', value: 'SSL5S2' },
  { name: 'SSL5S3', value: 'SSL5S3' },
  { name: 'SSL6S1', value: 'SSL6S1' },
  { name: 'SSL6S5', value: 'SSL6S5' },
  { name: 'SSL7S3', value: 'SSL7S3' },
  { name: 'STEACHER', value: 'STEACHER' },
  { name: 'TB1S1', value: 'TB1S1' },
  { name: 'TB1S2', value: 'TB1S2' },
  { name: 'TB2S1', value: 'TB2S1' },
  { name: 'TB2S2', value: 'TB2S2' },
  { name: 'TB2S3', value: 'TB2S3' },
  { name: 'TB2S4', value: 'TB2S4' },
  { name: 'TB3S1', value: 'TB3S1' },
  { name: 'TB3S2', value: 'TB3S2' },
  { name: 'TB3S3', value: 'TB3S3' },
  { name: 'TB3S4', value: 'TB3S4' }
]

export const staffPositionDropDown = [
  { name: 'Chief Executive Officer', value: 'Chief Executive Officer' },
  { name: 'Children Services EmployeeL1P1', value: 'Children Services EmployeeL1P1' },
  { name: 'Children Services EmployeeL2P1', value: 'Children Services EmployeeL2P1' },
  { name: 'Children Services EmployeeL2P2', value: 'Children Services EmployeeL2P2' },
  { name: 'Children Services EmployeeL4P3', value: 'Children Services EmployeeL4P3' },
  { name: 'Children Services EmployeeL6P4', value: 'Children Services EmployeeL6P4' },
  { name: 'Children Services EmployeeLP4', value: 'Children Services EmployeeLP4' },
  { name: 'Children Services SBTraining', value: 'Children Services SBTraining' },
  { name: 'Children ServicesEmployeeL4AP1', value: 'Children ServicesEmployeeL4AP1' },
  { name: 'Cleaning Grounds Staff Level 1', value: 'Cleaning Grounds Staff Level 1' },
  { name: 'Cleaning Grounds Staff Level 2', value: 'Cleaning Grounds Staff Level 2' },
  { name: 'Cleaning Grounds Staff Level 5', value: 'Cleaning Grounds Staff Level 5' },
  { name: 'College Bus Driver', value: 'College Bus Driver' },
  { name: 'College Operations Coordinator', value: 'College Operations Coordinator' },
  { name: 'Dean of Student Support', value: 'Dean of Student Support' },
  { name: 'Executive Assistant', value: 'Executive Assistant' },
  { name: 'Head of Distance Learning Educ', value: 'Head of Distance Learning Educ' },
  { name: 'Head of Faculty', value: 'Head of Faculty' },
  { name: 'Junior- 20', value: 'Junior- 20' },
  { name: 'Junior-18', value: 'Junior-18' },
  { name: 'Junior-19', value: 'Junior-19' },
  { name: 'Junior-Adult 1.1', value: 'Junior-Adult 1.1' },
  { name: 'Level 1 Step 1 Age 19', value: 'Level 1 Step 1 Age 19' },
  { name: 'Level 2 Step 1 Age 19', value: 'Level 2 Step 1 Age 19' },
  { name: 'Nursing Services G1 Step1', value: 'Nursing Services G1 Step1' },
  { name: 'Nursing Services G2 Step2', value: 'Nursing Services G2 Step2' },
  { name: 'Outside EBA - WHS C&I Officer', value: 'Outside EBA - WHS C&I Officer' },
  { name: 'Outside EBA BS Manager', value: 'Outside EBA BS Manager' },
  { name: 'Outside EBA Facility and Maint', value: 'Outside EBA Facility and Maint' },
  { name: 'Outside EBA Facility Manager', value: 'Outside EBA Facility Manager' },
  { name: 'Outside EBA Head of HR', value: 'Outside EBA Head of HR' },
  { name: 'Outside EBA Inventory&WHS Mgr', value: 'Outside EBA Inventory&WHS Mgr' },
  { name: 'Senior Teacher', value: 'Senior Teacher' },
  { name: 'Stream 2 L1 Paypoint 02', value: 'Stream 2 L1 Paypoint 02' },
  { name: 'Stream 3 DSL1SL2 Paypoint 23', value: 'Stream 3 DSL1SL2 Paypoint 23' },
  { name: 'Stream 3 DSL2 Paypoint 33', value: 'Stream 3 DSL2 Paypoint 33' },
  { name: 'Stream 3 DSL2 Paypoint 34', value: 'Stream 3 DSL2 Paypoint 34' },
  { name: 'Stream 3 DSL3SL3 Paypoint 33', value: 'Stream 3 DSL3SL3 Paypoint 33' },
  { name: 'Stream 3 DSL3SL3 Paypoint 35', value: 'Stream 3 DSL3SL3 Paypoint 35' },
  { name: 'Stream 3 SL1 Paypoint 13', value: 'Stream 3 SL1 Paypoint 13' },
  { name: 'Support Staff Level 1 Step 1', value: 'Support Staff Level 1 Step 1' },
  { name: 'Support Staff Level 2 Step 1', value: 'Support Staff Level 2 Step 1' },
  { name: 'Support Staff Level 2 Step 2', value: 'Support Staff Level 2 Step 2' },
  { name: 'Support Staff Level 2 Step 3', value: 'Support Staff Level 2 Step 3' },
  { name: 'Support Staff Level 3 Step 1', value: 'Support Staff Level 3 Step 1' },
  { name: 'Support Staff Level 3 Step 2', value: 'Support Staff Level 3 Step 2' },
  { name: 'Support Staff Level 3 Step 3', value: 'Support Staff Level 3 Step 3' },
  { name: 'Support Staff Level 3 Step 4', value: 'Support Staff Level 3 Step 4' },
  { name: 'Support Staff Level 4 Step 1', value: 'Support Staff Level 4 Step 1' },
  { name: 'Support Staff Level 4 Step 2', value: 'Support Staff Level 4 Step 2' },
  { name: 'Support Staff Level 4 Step 3', value: 'Support Staff Level 4 Step 3' },
  { name: 'Support Staff Level 5 Step 1', value: 'Support Staff Level 5 Step 1' },
  { name: 'Support Staff Level 5 Step 2', value: 'Support Staff Level 5 Step 2' },
  { name: 'Support Staff Level 5 Step 3', value: 'Support Staff Level 5 Step 3' },
  { name: 'Support Staff Level 6 Step 1', value: 'Support Staff Level 6 Step 1' },
  { name: 'Support Staff Level 6 Step 5', value: 'Support Staff Level 6 Step 5' },
  { name: 'Support Staff Level 7 Step 3', value: 'Support Staff Level 7 Step 3' },
  { name: 'Teacher Band 1 Step 1', value: 'Teacher Band 1 Step 1' },
  { name: 'Teacher Band 1 Step 2', value: 'Teacher Band 1 Step 2' },
  { name: 'Teacher Band 2 Step 1', value: 'Teacher Band 2 Step 1' },
  { name: 'Teacher Band 2 Step 2', value: 'Teacher Band 2 Step 2' },
  { name: 'Teacher Band 2 Step 3', value: 'Teacher Band 2 Step 3' },
  { name: 'Teacher Band 2 Step 4', value: 'Teacher Band 2 Step 4' },
  { name: 'Teacher Band 3 Step 1', value: 'Teacher Band 3 Step 1' },
  { name: 'Teacher Band 3 Step 2', value: 'Teacher Band 3 Step 2' },
  { name: 'Teacher Band 3 Step 3', value: 'Teacher Band 3 Step 3' },
  { name: 'Teacher Band 3 Step 4', value: 'Teacher Band 3 Step 4' }
]


export const positionTitleDropDown = [
  { name: 'Academy Assistant / Coach - Technology', value: 'Academy Assistant / Coach - Technology' },
  { name: 'Academy Coordinator - Hifz Quran Memorisation (P-Y12)', value: 'Academy Coordinator - Hifz Quran Memorisation (P-Y12)' },
  { name: 'Academy Coordinator - Sport (P-Y12)', value: 'Academy Coordinator - Sport (P-Y12)' },
  { name: 'Academy Coordinator – Technology (P to Y12)', value: 'Academy Coordinator – Technology (P to Y12)' },
  { name: 'Acting Head of Secondary Years 10-12', value: 'Acting Head of Secondary Years 10-12' },
  { name: 'Acting Head of Secondary Years 7-9', value: 'Acting Head of Secondary Years 7-9' },
  { name: 'Administration - HR Assistant', value: 'Administration - HR Assistant' },
  { name: 'Administration IT Support Officer', value: 'Administration IT Support Officer' },
  { name: 'Administration Officer', value: 'Administration Officer' },
  { name: 'Administration Officer - Receptionist - Casual', value: 'Administration Officer - Receptionist - Casual' },
  { name: 'Administration Support', value: 'Administration Support' },
  { name: 'Administrative Leadership - Head of Finance & Operations', value: 'Administrative Leadership - Head of Finance & Operations' },
  { name: 'Administrative Leadership - Head of ICT & Security', value: 'Administrative Leadership - Head of ICT & Security' },
  { name: 'Aide Assistant - Welfare', value: 'Aide Assistant - Welfare' },
  { name: 'Board Secretary', value: 'Board Secretary' },
  { name: 'Casual School Nurse', value: 'Casual School Nurse' },
  { name: 'Casual Sports Coach', value: 'Casual Sports Coach' },
  { name: 'Chief Learning Officer (CLO)', value: 'Chief Learning Officer (CLO)' },
  { name: 'College Bus Driver', value: 'College Bus Driver' },
  { name: 'College Operations Coordinator', value: 'College Operations Coordinator' },
  { name: 'College Store Manager', value: 'College Store Manager' },
  { name: 'Curriculum Coordinator (Y3-6) | Primary Teacher', value: 'Curriculum Coordinator (Y3-6) | Primary Teacher' },
  { name: 'Curriculum Coordinator- Arabic (Prep to Year 12)', value: 'Curriculum Coordinator- Arabic (Prep to Year 12)' },
  { name: 'Director of Islamic Studies', value: 'Director of Islamic Studies' },
  { name: 'Director of Student Support', value: 'Director of Student Support' },
  { name: 'Executive - Chief Executive Officer', value: 'Executive - Chief Executive Officer' },
  { name: 'Executive Assistant', value: 'Executive Assistant' },
  { name: 'Facilities - Caretaker', value: 'Facilities - Caretaker' },
  { name: 'Facilities - Facilities and Maintenance Officer', value: 'Facilities - Facilities and Maintenance Officer' },
  { name: 'Facilities - Groundsman', value: 'Facilities - Groundsman' },
  { name: 'Facilities - WHS Compliance and Infrastructure Officer', value: 'Facilities - WHS Compliance and Infrastructure Officer' },
  { name: 'Finance - Accounts Administration Payable', value: 'Finance - Accounts Administration Payable' },
  { name: 'Finance - Accounts Administration Receivable', value: 'Finance - Accounts Administration Receivable' },
  { name: 'Finance - Finance Officer', value: 'Finance - Finance Officer' },
  { name: 'Head of Distance Learning Education', value: 'Head of Distance Learning Education' },
  { name: 'Head of Facilities and Infrastructure', value: 'Head of Facilities and Infrastructure' },
  { name: 'Head of HR', value: 'Head of HR' },
  { name: 'Head of Primary', value: 'Head of Primary' },
  { name: 'Head of Secondary', value: 'Head of Secondary' },
  { name: 'HR Administrator', value: 'HR Administrator' },
  { name: 'ICT - System Administrator', value: 'ICT - System Administrator' },
  { name: 'ICT Technician', value: 'ICT Technician' },
  { name: 'IT Student Placement', value: 'IT Student Placement' },
  { name: 'IT Systems and Automation Officer', value: 'IT Systems and Automation Officer' },
  { name: 'Library -  Teacher Librarian Primary Coordinator & Secondary Coordinator', value: 'Library -  Teacher Librarian Primary Coordinator & Secondary Coordinator' },
  { name: 'Library - Librarian', value: 'Library - Librarian' },
  { name: 'Library - Technician & Technologies Support Officer', value: 'Library - Technician & Technologies Support Officer' },
  { name: 'Library - Technician/Aide', value: 'Library - Technician/Aide' },
  { name: 'OHSC Educator', value: 'OHSC Educator' },
  { name: 'OSHC Co-ordinator', value: 'OSHC Co-ordinator' },
  { name: 'OSHC Educator', value: 'OSHC Educator' },
  { name: 'OSHC School Based Trainee - Year 12', value: 'OSHC School Based Trainee - Year 12' },
  { name: 'OSHC Senior Educator', value: 'OSHC Senior Educator' },
  { name: 'Primary & Secondary Aide Assistant - English Language Support', value: 'Primary & Secondary Aide Assistant - English Language Support' },
  { name: 'Primary & Secondary Aide Assistant - Healthcentre', value: 'Primary & Secondary Aide Assistant - Healthcentre' },
  { name: 'Primary & Secondary Teacher - Islamic Hifz', value: 'Primary & Secondary Teacher - Islamic Hifz' },
  { name: 'Primary Aide Assistant - Classroom', value: 'Primary Aide Assistant - Classroom' },
  { name: 'Primary Aide Assistant - Learning Support', value: 'Primary Aide Assistant - Learning Support' },
  { name: 'Primary Aide Assistant - Learning Support Coordinator P-Y2', value: 'Primary Aide Assistant - Learning Support Coordinator P-Y2' },
  { name: 'Primary Aide Assistant - Learning Support Prep', value: 'Primary Aide Assistant - Learning Support Prep' },
  { name: 'Primary Aide Assistant - Learning Support Y1', value: 'Primary Aide Assistant - Learning Support Y1' },
  { name: 'Primary Aide Assistant - Learning Support Y3,Y4', value: 'Primary Aide Assistant - Learning Support Y3,Y4' },
  { name: 'Primary Aide Assistant - Learning Support Y6', value: 'Primary Aide Assistant - Learning Support Y6' },
  { name: 'Primary Aide Assistant - Learning SupportY5', value: 'Primary Aide Assistant - Learning SupportY5' },
  { name: 'Primary Aide Assistant - PE', value: 'Primary Aide Assistant - PE' },
  { name: 'Primary and Secondary Teacher - Islamic Hifz 0.6 FTE', value: 'Primary and Secondary Teacher - Islamic Hifz 0.6 FTE' },
  { name: 'Primary Teacher', value: 'Primary Teacher' },
  { name: 'Primary Teacher - Arabic', value: 'Primary Teacher - Arabic' },
  { name: 'Primary Teacher - Diverse Learning Coordinator', value: 'Primary Teacher - Diverse Learning Coordinator' },
  { name: 'Primary Teacher - Eucalyptus House Coordinator', value: 'Primary Teacher - Eucalyptus House Coordinator' },
  { name: 'Primary Teacher - Intensive EALD & Reading Recovery', value: 'Primary Teacher - Intensive EALD & Reading Recovery' },
  { name: 'Primary Teacher - Islamic Studies', value: 'Primary Teacher - Islamic Studies' },
  { name: 'Primary Teacher - IT', value: 'Primary Teacher - IT' },
  { name: 'Primary Teacher - Prep Level Coordinator', value: 'Primary Teacher - Prep Level Coordinator' },
  { name: 'Primary Teacher - Relief Teacher', value: 'Primary Teacher - Relief Teacher' },
  { name: 'Primary Teacher - Wattle House Coordinator', value: 'Primary Teacher - Wattle House Coordinator' },
  { name: 'Primary Teacher - Year 1 Level & Pine House Coordinator', value: 'Primary Teacher - Year 1 Level & Pine House Coordinator' },
  { name: 'Primary Teacher - Year 2 Level Coordinator', value: 'Primary Teacher - Year 2 Level Coordinator' },
  { name: 'Primary Teacher - Year 3 Level Coordinator', value: 'Primary Teacher - Year 3 Level Coordinator' },
  { name: 'Primary Teacher - Year 4 Level Coordinator & Excellence Program Coordinator – Debating', value: 'Primary Teacher - Year 4 Level Coordinator & Excellence Program Coordinator – Debating' },
  { name: 'Primary Teacher - Year 5 Level Coordinator - STEACHER', value: 'Primary Teacher - Year 5 Level Coordinator - STEACHER' },
  { name: 'Primary Teacher - Year 6 Level Coordinator & Excellence Program Coordinator – Debating', value: 'Primary Teacher - Year 6 Level Coordinator & Excellence Program Coordinator – Debating' },
  { name: 'Primary Teacher & Assistant Curriculum Coordinator -Primary', value: 'Primary Teacher & Assistant Curriculum Coordinator -Primary' },
  { name: 'Primary Teacher & Excellence Program Coordinator – Islamic', value: 'Primary Teacher & Excellence Program Coordinator – Islamic' },
  { name: 'Primary Teacher and Dean of Students', value: 'Primary Teacher and Dean of Students' },
  { name: 'Relief Teacher', value: 'Relief Teacher' },
  { name: 'Relief Teacher - Islamic', value: 'Relief Teacher - Islamic' },
  { name: 'Relief Teacher - Prep to Year 7 (Islamic)', value: 'Relief Teacher - Prep to Year 7 (Islamic)' },
  { name: 'Relief Teacher - Primary', value: 'Relief Teacher - Primary' },
  { name: 'Relief Teacher - Primary & Secondary', value: 'Relief Teacher - Primary & Secondary' },
  { name: 'Relief Teacher - Secondary', value: 'Relief Teacher - Secondary' },
  { name: 'Relief Teacher Aide', value: 'Relief Teacher Aide' },
  { name: 'School Administrator - College Receptionist', value: 'School Administrator - College Receptionist' },
  { name: 'School Administrator - College Store Officer', value: 'School Administrator - College Store Officer' },
  { name: 'School Administrator - Digital Marketing', value: 'School Administrator - Digital Marketing' },
  { name: 'School Administrator - Enrolments Experience Officer', value: 'School Administrator - Enrolments Experience Officer' },
  { name: 'School Administrator - Primary School Administration Officer', value: 'School Administrator - Primary School Administration Officer' },
  { name: 'School Administrator - Secondary Administration Officer', value: 'School Administrator - Secondary Administration Officer' },
  { name: 'School Administrator - Secondary Student Pathways', value: 'School Administrator - Secondary Student Pathways' },
  { name: 'School Administrator - Secondary Student Services Officer', value: 'School Administrator - Secondary Student Services Officer' },
  { name: 'School Administrator - Sport', value: 'School Administrator - Sport' },
  { name: 'School Administrator - Student Welfare Administrator', value: 'School Administrator - Student Welfare Administrator' },
  { name: 'Secondary - Head of Faculty - (SMDTT)', value: 'Secondary - Head of Faculty - (SMDTT)' },
  { name: 'Secondary - Head of Faculty (HEAL and HPE)', value: 'Secondary - Head of Faculty (HEAL and HPE)' },
  { name: 'Secondary Aide Assistant - Learning Support', value: 'Secondary Aide Assistant - Learning Support' },
  { name: 'Secondary Laboratory Technician', value: 'Secondary Laboratory Technician' },
  { name: 'Secondary School Administrator', value: 'Secondary School Administrator' },
  { name: 'Secondary Teacher', value: 'Secondary Teacher' },
  { name: 'Secondary Teacher - Arabic', value: 'Secondary Teacher - Arabic' },
  { name: 'Secondary Teacher - Dean of Students', value: 'Secondary Teacher - Dean of Students' },
  { name: 'Secondary Teacher - Design & Technology', value: 'Secondary Teacher - Design & Technology' },
  { name: 'Secondary Teacher - English', value: 'Secondary Teacher - English' },
  { name: 'Secondary Teacher - English & Eucalyptus House Coordinator', value: 'Secondary Teacher - English & Eucalyptus House Coordinator' },
  { name: 'Secondary Teacher - HPE', value: 'Secondary Teacher - HPE' },
  { name: 'Secondary Teacher - HPE & Bottle Brush House Coordinator', value: 'Secondary Teacher - HPE & Bottle Brush House Coordinator' },
  { name: 'Secondary Teacher - HPE & Wattle House Coordinator', value: 'Secondary Teacher - HPE & Wattle House Coordinator' },
  { name: 'Secondary Teacher - Humanities', value: 'Secondary Teacher - Humanities' },
  { name: 'Secondary Teacher - Humanities & Pine House Coordinator', value: 'Secondary Teacher - Humanities & Pine House Coordinator' },
  { name: 'Secondary Teacher - Islamic Studies', value: 'Secondary Teacher - Islamic Studies' },
  { name: 'Secondary Teacher - Maths', value: 'Secondary Teacher - Maths' },
  { name: 'Secondary Teacher - Science', value: 'Secondary Teacher - Science' },
  { name: 'Secondary Teacher - Technology &  Pine House Coordinator', value: 'Secondary Teacher - Technology &  Pine House Coordinator' },
  { name: 'Secondary Teacher - Visual Art', value: 'Secondary Teacher - Visual Art' },
  { name: 'Secondary Teacher - Visual Arts & Wattle House Coordinator', value: 'Secondary Teacher - Visual Arts & Wattle House Coordinator' },
  { name: 'Secondary Teacher & Diverse Learning Coordinator', value: 'Secondary Teacher & Diverse Learning Coordinator' },
  { name: 'Senior Pathways and Careers Advisor', value: 'Senior Pathways and Careers Advisor' },
  { name: 'Student Counsellor', value: 'Student Counsellor' },
  { name: 'Teacher Aide - Arabic', value: 'Teacher Aide - Arabic' },
  { name: 'Welfare - School Nurse term-time', value: 'Welfare - School Nurse term-time' },
  { name: 'Welfare - Youth Guidance Officer', value: 'Welfare - Youth Guidance Officer' },
  { name: 'Wellbeing Coordinator', value: 'Wellbeing Coordinator' },
  { name: 'Youth Support Worker', value: 'Youth Support Worker' }
]

export const yearGroupDropDown = [
  { name: '0', value: 0 },
  { name: '1', value: 1 },
  { name: '2', value: 2 },
  { name: '3', value: 3 },
  { name: '4', value: 4 },
  { name: '5', value: 5 },
  { name: '6', value: 6 },
  { name: '7', value: 7 },
  { name: '8', value: 8 },
  { name: '9', value: 9 },
  { name: '10', value: 10 },
  { name: '11', value: 11 },
  { name: '12', value: 12 },
]

export const classCodeDropDown = [
  { name: 'A', value: 'A' },
  { name: 'B', value: 'B' },
  { name: 'C', value: 'C' },
  { name: 'D', value: 'D' },
  { name: 'E', value: 'E' },
  { name: 'F', value: 'F' },
  { name: 'G', value: 'G' },
  { name: 'H', value: 'H' },
  { name: 'J', value: 'J' },
  { name: 'K', value: 'K' },
  { name: 'M', value: 'M' },
  { name: 'N', value: 'N' },
  { name: 'P', value: 'P' },
  { name: 'R', value: 'R' },
  { name: 'T', value: 'T' },
]

export const studentStatusDropDown = [
  { name: 'Active', value: 'Active' },
  { name: 'Inactive', value: 'Inactive' },
]

// House dropdown
export const houseDropDown = [
  { name: 'Bottlebrush', value: 'BOTTLEBRUSH' },
  { name: 'Eucalyptus', value: 'EUCALYPTUS' },
  { name: 'Pine', value: 'PINE' },
  { name: 'Wattle', value: 'WATTLE' }
]
